---
- name: user management play1 on localhost
  hosts: localhost
  connection: local

  vars:
    valid_hostnames_p1: ""
  vars_files:
       - external_vars.yml  

  tasks:
  - name: Fail when the csvfilename is empty
    fail:
            msg: "No csv file name mentioned"
    when:
        - var_inputcsvfile|length == 0

  - name: Get Input file
    include_role:
      name: user_management_role
      tasks_from: get_inputfile.yml
    vars:    
          var_dirtocheckout: "{{ var_directory }}"
  - name: read CSV file
    include_role:
     name: user_management_role
     tasks_from: read_csv.yml
    vars:
      csv_file_name: "{{ var_directory }}/{{ var_inputcsvfile }}"

  - debug:
       msg: "data from csv file in role file = {{ csvresults }} "

  - name: create hostname variable
    include_role:
      name: user_management_role
      tasks_from: valid_hostnames.yml

  - debug:
      msg: "valid hostnames = {{ valid_hostnames_p1 }}"
  - name: Fail when no tasks or no valid hostnames
    fail:
       msg: " No  {{ var_actionfrommainfile }} tasks or no valid hostnames"
    when: valid_hostnames_p1|length == 0

