---
  - name: replace trailing space
    replace:
          path: "{{ csv_file_name }}"
          regexp: ' ,'
          replace: ','
  - name: Read users from CSV file and return a list
    read_csv:
            path: "{{ csv_file_name }}"
            fieldnames: "{{ csv_fields }}"
            delimiter: ','
            skipinitialspace: yes
    register: usersvar
  - name: Set number of fields
    set_fact:
       var_numberoffields: "{{ csv_fields.split(',')|length }}"  
       csvresults: []
       var_numberoffieldsfromcsv: "{{ (usersvar.list| first).values()|select()|list|length }}"
  - debug:
          msg: "Number of fields should be : {{ var_numberoffields }} {{ var_numberoffieldsfromcsv }} "
  - fail:
        msg: "Number of fields in CSV should be {{ var_numberoffields }}. In CSV it is {{ var_numberoffieldsfromcsv }}"        
    when:    
       - var_numberoffieldsfromcsv != var_numberoffields
  - name: Removing first element
    set_fact:
            csvresults: "{{ csvresults | default([]) | union([item]) }}"
    loop: "{{ usersvar.list }}"
    loop_control:
         index_var: index
    when:
       - index > 0

  - debug:
      msg: "AFTER removing first element ---------------- {{ csvresults }}"
