---
  
  - name: check if user alread exists or not
    shell: "cat /etc/passwd|grep -w {{ list_item.UserID }}|wc -l"
    register: user_output
    ignore_errors: true

  - debug:
          msg: "user output ===================== {{ user_output }} "
  - set_fact:
          var_uid_exists: "{{ (user_output.stdout == '1')|ternary(true,false) }}"
          var_validation: false
          var_readable_format: ""
  - set_fact:
          var_validation: true   
          var_readable_format: "{{ '%Y-%m-%d' | strftime(list_item.Age_date|default(0)) }}"
    ignore_errors: true   
    when:
       - list_item.Agedate is defined and list_item.Agedate|length >0 and list_item.Agedate|int(-1)!=-1
  - debug:
          msg: " expirydays:{{list_item.Expirydays|int(-1) }}  {{ list_item.Agedate|int(-1) }}"         
  - set_fact:
           var_validation: false
    ignore_errors: true
    when:
        - list_item.Expirydays!="" and list_item.Expirydays|int(-1)==-1 
            
  - name: Extend validity of userid 
    shell: "/usr/bin/chage -d '{{ var_readable_format }}' -M {{ list_item.Expirydays|default(90) }} {{ list_item.UserID }}"
    register: ageresult
    ignore_errors: true    
    when:
      - var_uid_exists and var_validation

  - debug:
      msg: "================Age change result ==== {{ ageresult| default([]) }} "
  - set_fact:
            var_output_txt: "{{ var_output_txt+ list_item[keysitem]+', ' }}"
    loop: "{{ var_csv_fields.split(',') }}"   
    loop_control:
        loop_var: keysitem
  - debug:
       msg: " new output:{{ var_output_txt }}"      


  - set_fact:
       var_output_txt: "{{ var_output_txt +', '+ 'Change age Successful' + '\n' }}"
    when:
       - var_uid_exists and var_validation
       - ageresult.stderr is not defined or ageresult.stderr|length==0 
  - set_fact:
      var_output_txt: "{{ var_output_txt + 'Userid doesnt exist' + '\n' }}"         
    when: 
      - var_uid_exists == false
  - set_fact:      
      var_output_txt: "{{ var_output_txt + 'Change age failed' + ageresult.stderr|default(' ') }}"
    when:  
      - var_uid_exists and var_validation and ageresult is defined and ageresult.stderr|length>0
  - set_fact:
       var_output_txt: "{{ var_output_txt + 'Age date/expiry format is incorrect' + '\n' }}"
    when:
       - var_uid_exists and var_validation==false 
